-- ==============================================================================
-- WebsiteDetailsScraper - Supabase PostgreSQL Schema
-- ==============================================================================
-- Run this in your Supabase Dashboard:
-- 1. Go to your Supabase project (https://supabase.com/dashboard)
-- 2. Click "SQL Editor" in the left sidebar
-- 3. Click "New query", paste this entire file, and click "Run" (or Ctrl+Enter)
-- ==============================================================================

-- 1. Create the `leads` table with all contactability and intelligence fields
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    -- Deterministic identity key for deduplication and conflict-free upserts
    identity_key TEXT UNIQUE NOT NULL,
    
    -- Search & Ranking
    search_rank TEXT,
    keyword TEXT,
    
    -- Business Information
    business_name TEXT NOT NULL,
    category TEXT,
    review_rating NUMERIC(3, 2),
    review_count TEXT,
    hours_status TEXT,
    address TEXT,
    google_maps_directions TEXT,
    
    -- Contact & Web Discovery
    phone TEXT,
    website TEXT,
    email TEXT,
    contact_page TEXT,
    about_page TEXT,
    team_page TEXT,
    owner_name_candidates TEXT,
    review_snippet TEXT,
    pages_checked INTEGER DEFAULT 0,
    status TEXT,
    
    -- Intelligence & Scoring (0-100 Contactability)
    lead_score INTEGER DEFAULT 0,
    data_confidence TEXT DEFAULT 'Low', -- 'High', 'Medium', 'Low'
    data_sources TEXT DEFAULT 'Google Maps',
    duplicate_count INTEGER DEFAULT 1,
    merged_ranks TEXT
);

-- 2. Performance Indexes for Search, Filtering & Scoring
CREATE INDEX IF NOT EXISTS idx_leads_identity_key ON public.leads(identity_key);
CREATE INDEX IF NOT EXISTS idx_leads_lead_score ON public.leads(lead_score DESC);
CREATE INDEX IF NOT EXISTS idx_leads_data_confidence ON public.leads(data_confidence);
CREATE INDEX IF NOT EXISTS idx_leads_keyword ON public.leads(keyword);
CREATE INDEX IF NOT EXISTS idx_leads_phone ON public.leads(phone) WHERE phone IS NOT NULL AND phone != '';
CREATE INDEX IF NOT EXISTS idx_leads_email ON public.leads(email) WHERE email IS NOT NULL AND email != '';
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON public.leads(created_at DESC);

-- 3. Automatically update `updated_at` on row updates
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_set_leads_updated_at ON public.leads;
CREATE TRIGGER trigger_set_leads_updated_at
BEFORE UPDATE ON public.leads
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- 4. Row Level Security (RLS) Configuration
-- Enables RLS while providing full access for authenticated API keys and anon keys
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow select for anon and service role" ON public.leads;
CREATE POLICY "Allow select for anon and service role"
ON public.leads FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow insert for anon and service role" ON public.leads;
CREATE POLICY "Allow insert for anon and service role"
ON public.leads FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update for anon and service role" ON public.leads;
CREATE POLICY "Allow update for anon and service role"
ON public.leads FOR UPDATE
USING (true)
WITH CHECK (true);

-- 5. Optional Search Runs Table (tracks searches and timestamps)
CREATE TABLE IF NOT EXISTS public.search_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    query TEXT NOT NULL,
    mode TEXT DEFAULT 'places',
    lead_count INTEGER DEFAULT 0,
    source TEXT
);

ALTER TABLE public.search_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for search_runs" ON public.search_runs;
CREATE POLICY "Allow all for search_runs"
ON public.search_runs FOR ALL
USING (true)
WITH CHECK (true);
